// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfmjbsgwnvcdskascoeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmbWpic2d3bnZjZHNrYXNjb2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTM4ODQsImV4cCI6MjA3Mjg2OTg4NH0.20cF5OSVpAFlZ4_HC-b8xawZWal_xw-4nZrsqZXTWQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});